// Generated by CoffeeScript 1.4.0
(function() {
  var Badge, COMMIT_DISPLAYED_ID_LENGTH, COMMIT_MSG_MAX_LENGTH, DEFAULT_BRANCH_NAME, HIDE_FILES_TXT, SHOW_FILES_TXT, client_id, client_secret, commit_msg, devel, mainpage, parseDate, truncate;

  client_id = "";

  client_secret = "";

  client_id = "ffc2b97509f21108d9f1";

  client_secret = "a18681acb21531b49527198b86f5350f6320cfb1";

  devel = "&client_id=" + client_id + "&client_secret=" + client_secret;

  DEFAULT_BRANCH_NAME = "master";

  COMMIT_MSG_MAX_LENGTH = 120;

  COMMIT_DISPLAYED_ID_LENGTH = 8;

  SHOW_FILES_TXT = 'Show more';

  HIDE_FILES_TXT = 'Show less';

  truncate = function(string, length, truncation) {
    if (length == null) {
      length = 30;
    }
    if (truncation == null) {
      truncation = "...";
    }
    return string.slice(0, +length + 1 || 9e9);
  };

  commit_msg = function(string) {
    return truncate(string.replace(/\n.*/g, "").replace(/\r.*/g, ""), COMMIT_MSG_MAX_LENGTH);
  };

  parseDate = function(dateTime) {
    return dateTime.replace(/T.*/, "");
  };

  Badge = (function() {
    var api_commit, api_repo, commit_url, name, selector;

    selector = api_commit = api_repo = name = commit_url = "";

    function Badge(username, repo, branch) {
      this.username = username;
      this.repo = repo;
      this.branch = branch != null ? branch : DEFAULT_BRANCH_NAME;
      this.api_commit = "https://api.github.com/repos/" + this.username + "/" + this.repo + "/commits/" + this.branch + "?callback=?" + devel;
      this.api_repo = "https://api.github.com/repos/" + this.username + "/" + this.repo + "?callback=?" + devel;
      this.name = "" + username + "_" + (repo.replace(/\./g, '-'));
      this.selector = "#" + this.name;
      $("#gcb-template").clone().appendTo("#gcb-container").attr("id", this.name);
      $(this.selector).appendTo("#gcb-container").show();
      this.parse_commit();
      this.parse_repo();
    }

    Badge.prototype.parse_commit = function() {
      var _this = this;
      return $.getJSON(this.api_commit, function(data) {
        var added, file, modified, myAdded, myModified, myRemoved, removed, _i, _j, _k, _l, _len, _len1, _len2, _len3, _ref;
        if (data.meta && data.meta.status === 403) {
          console.log("Something went wrong requesting the commits for " + _this.api_commit + ": " + data.data.message);
          $(selector).text("Error: " + data.data.message);
          return;
        }
        $("div.diffline img.gravatar", _this.selector).attr({
          "src": data.data.committer.avatar_url,
          alt: ""
        });
        _this.commit_url = "https://github.com/" + _this.username + "/" + _this.repo + "/commit/" + data.data.sha;
        added = [];
        modified = [];
        removed = [];
        _ref = data.data.files;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          file = _ref[_i];
          switch (file.status) {
            case "modified":
              modified.push(file);
              break;
            case "added":
              added.push(file);
              break;
            default:
              removed.push(file);
          }
        }
        $("div.username", _this.selector).append(" (branch: " + _this.branch + ")");
        $("div.diffline a.badge", _this.selector).attr({
          "href": _this.commit_url
        }).text(truncate(data.data.sha, COMMIT_DISPLAYED_ID_LENGTH, ""));
        $("span.text-date", _this.selector).text(" " + (parseDate(data.data.commit.committer.date)));
        $("span.committer", _this.selector).text(data.data.commit.committer.name);
        $("span.email", _this.selector).text(" <" + data.data.commit.committer.email + ">");
        $("div.commitmessage", _this.selector).text(commit_msg(data.data.commit.message));
        $("div.commitmessagelong", _this.selector).text(data.data.commit.message).hide();
        $("div.diffstat a.showMoreLink", _this.selector).attr("id", "showMoreLink_" + _this.name);
        $("div.diffstat span.diffadded", _this.selector).before(added.length);
        $("div.diffstat span.diffremoved", _this.selector).before(removed.length);
        $("div.diffstat span.diffmodified", _this.selector).before(modified.length);
        $("div.filelist", _this.selector).attr({
          id: "files_" + _this.name
        });
        if (added.length > 0) {
          $("div.diffadded span.diffadded", _this.selector).show();
        }
        for (_j = 0, _len1 = added.length; _j < _len1; _j++) {
          myAdded = added[_j];
          $("div.diffadded ul", _this.selector).append($("<li/>").text(myAdded.filename).append($("<span class='diffadded'/>").text(" (" + myAdded.changes + ")")));
        }
        if (removed.length > 0) {
          $("div.diffremoved span.diffremoved", _this.selector).show();
        }
        for (_k = 0, _len2 = removed.length; _k < _len2; _k++) {
          myRemoved = removed[_k];
          $("div.diffremoved ul", _this.selector).append($("<li/>").text(myRemoved.filename).append($("<span class='diffremoved'/>").text(" (" + myRemoved.changes + ")")));
        }
        if (modified.length > 0) {
          $("div.diffmodified span.diffmodified", _this.selector).show();
        }
        for (_l = 0, _len3 = modified.length; _l < _len3; _l++) {
          myModified = modified[_l];
          $("div.diffmodified ul", _this.selector).append($("<li/>").text(myModified.filename).append($("<span class='diffmodified'/>").text(" (" + myModified.changes + ")")));
        }
        $("#showMoreLink_" + _this.name).click(function() {
          $("#files_" + _this.name).toggle();
          $("" + _this.selector + " > .commitmessagelong").toggle();
          $("" + _this.selector + " > .commitmessage").toggle();
          if ($("#showMoreLink_" + _this.name).text() === SHOW_FILES_TXT) {
            $("#showMoreLink_" + _this.name).text(HIDE_FILES_TXT);
          } else {
            $("#showMoreLink_" + _this.name).text(SHOW_FILES_TXT);
          }
          return false;
        });
        return $(_this.selector).click(function() {
          return $("#showMoreLink_" + _this.name).click();
        });
      });
    };

    Badge.prototype.parse_repo = function() {
      var _this = this;
      return $.getJSON(this.api_repo, function(data) {
        $("div.username a", _this.selector).text("" + _this.username + "/" + _this.repo).attr("href", data.data.html_url);
        return $("span.followers", _this.selector).text("(" + data.data.forks + " forks, " + data.data.watchers + " starred)");
      });
    };

    return Badge;

  })();

  mainpage = function() {
    return $("#gcb-container").load("html/badge.html", function() {
      var badgeData, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = Badges.length; _i < _len; _i++) {
        badgeData = Badges[_i];
        _results.push(new Badge(badgeData.username, badgeData.repo, badgeData.branch));
      }
      return _results;
    });
  };

  $('head').append($('<link rel="stylesheet" type="text/css" />').attr('href', 'css/style.css'));

  $(function() {
    return mainpage();
  });

}).call(this);
